// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYBzu6awKak0B_H_JFhoMu5tYNX5JjGLg',
    appId: '1:781069625118:web:53abd819facd4418a18b0f',
    messagingSenderId: '781069625118',
    projectId: 'chatbot-fqqm',
    authDomain: 'chatbot-fqqm.firebaseapp.com',
    storageBucket: 'chatbot-fqqm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8AMysKJ3ULiF58R3Qun38dxIonH_dYPI',
    appId: '1:781069625118:android:5e601ef484fd9a33a18b0f',
    messagingSenderId: '781069625118',
    projectId: 'chatbot-fqqm',
    storageBucket: 'chatbot-fqqm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwGd6d12q26B0EJzkSxDOPBF4EMOhsm0',
    appId: '1:781069625118:ios:f3e02690925ec430a18b0f',
    messagingSenderId: '781069625118',
    projectId: 'chatbot-fqqm',
    storageBucket: 'chatbot-fqqm.appspot.com',
    iosClientId: '781069625118-mld787r38qqehritcoa9f11njmmi8r1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot',
  );
}
